mqtt:
  host: ${MQTT_HOST:localhost}
  port: ${MQTT_PORT:1883}
  client-id: ${MQTT_CLIENT_ID:wallpad-controller}
  username: ${MQTT_USERNAME:hyeonpyo}
  password: ${MQTT_PASSWORD:password}
  ha-topic: ${MQTT_HA_TOPIC:commax}

spring:
  datasource:
    url: jdbc:sqlite:/app/mydb.db
    driver-class-name: org.sqlite.JDBC