spring:
  application:
    name: Wallpadcontroller
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update 
    open-in-view: false
  datasource:
    url: jdbc:sqlite:./mydb.db
    driver-class-name: org.sqlite.JDBC

mqtt:
  host: 192.168.50.192
  port: 1883
  client-id: wallpad-controller
  username: hyeonpyo
  password: J7QNgG6ta4%3OC,+U
  ha-topic: commax